# Generated by Django 5.1.3 on 2025-01-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_booked',
        ),
    ]
